### ISSUE TITLE
Find Dataset

### ISSUE THREAD

**Issue by aimanfatima** [aimanfatima/Minor-Project#1]
Task-1
Find a suitable dataset for this project.

**Comment by Naomi98** [comment]
Search for data sets on this Google Beta Search Bar:
https://toolbox.google.com/datasetsearch

**Comment by Naomi98** [comment]
This is a Memes Data set on Kaggle. Not all images provided are offensive but this is the kind of data set required. 
https://www.kaggle.com/sayangoswami/reddit-memes-dataset

(Have a look)

**Comment by Naomi98** [comment]
**Meme Data set (Possibly could be the one we could use)** -
- Contains offensive words and memes as well (not all)
- Approximately 170,000+ images in the data set

Issue with the data set:
When opened in the Word (.docx format), then each column is separated by space. However, on converting it to .csv file whole content is getting in one column only.

(Link describing the data set about how each image is to be extracted, etc.): 
http://www.michelecoscia.com/?page_id=422

Data set (Extract and open with Word or save as .csv and open in Excel):
[memes_total_time.zip](https://github.com/aimanfatima/Minor-Project/files/3828655/memes_total_time.zip)

**Comment by aimanfatima** [comment]
> **Meme Data set (Possibly could be the one we could use)** -
> 
> * Contains offensive words and memes as well (not all)
> * Approximately 170,000+ images in the data set
> 
> Issue with the data set:
> When opened in the Word (.docx format), then each column is separated by space. However, on converting it to .csv file whole content is getting in one column only.
> 
> (Link describing the data set about how each image is to be extracted, etc.):
> http://www.michelecoscia.com/?page_id=422
> 
> Data set (Extract and open with Word or save as .csv and open in Excel):
> [memes_total_time.zip](https://github.com/aimanfatima/Minor-Project/files/3828655/memes_total_time.zip)

This looks good.
We can open it in Notepad (opens as tab-separated columns)
I'll look into tab separation techniques. 

**Steps involved in order to extract the data from this dataset -** 

1. Write a script (shell script maybe?) to get the first column (i.e. meme_id ) of each row at a time
2. Put it in the URL given http://i.qkme.me/<meme_id>.jpg
3. Connect it with the corresponding page and download the image in the respective folder.

Or We may **directly** use the URL as well in our model.

**Comment by Naomi98** [comment]
> Or We may **directly** use the URL as well in our model.

I thought the same, just extracting the URLs for all the images could be useful too. Was not sure if directly using URLs is quite plausible though. If it is, this is good enough.

Do you already know how to use URLs directly or should I look into it?

**Comment by aimanfatima** [comment]
> Do you already know how to use URLs directly or should I look into it?

I'm quite sure that we can, though I never tried. Please look into it.

**Comment by aimanfatima** [comment]
I have made the necessary changes to the [dataset](https://github.com/aimanfatima/Minor-Project/tree/master/Dataset).

Added a separate column URL to the dataframe to "**data_with_urls.csv**"
Also, a separate csv file is also there with just one column (i.e. the url itself) "**url.csv**"

**Comment by Naomi98** [comment]
The images data set with images numbered from 1-1000 has been uploaded [here](https://github.com/aimanfatima/Minor-Project/tree/master/Dataset/Image-Dataset)
